/**
 * Difficulty tuning for the Bridge Game
 * Controls platform shrinking and forced movement ramps.
 */

export const DIFFICULTY_CONFIG = {
  PLATFORM_SHRINK_START_INDEX: 15,
  PLATFORM_SHRINK_EVERY: 5,
  PLATFORM_SHRINK_FACTOR: 0.9,
  PLATFORM_MIN_WIDTH_EARLY: 40,
  PLATFORM_MIN_WIDTH_LATE: 25,
  PLATFORM_MIN_WIDTH_LATE_INDEX: 15,
  PLATFORM_MOVE_START_INDEX: 10,
  PLATFORM_SPEED_START_INDEX: 10,
  PLATFORM_SPEED_EVERY: 10,
  PLATFORM_SPEED_INCREMENT: 0.03,
  PLATFORM_VARIANCE_START_INDEX: 15,
  PLATFORM_SPEED_VARIANCE_MIN: 0.98,
  PLATFORM_SPEED_VARIANCE_MAX: 1.02,
  PLATFORM_TARGET_MIN_DISTANCE: 70,
  PLATFORM_TARGET_MIN_DISTANCE_RATIO: 0.6,
} as const;
